-- MySQL Script generated by MySQL Workbench
-- Tue Apr  6 23:30:33 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema PuntoVenta
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `PuntoVenta` ;

-- -----------------------------------------------------
-- Schema PuntoVenta
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PuntoVenta` DEFAULT CHARACTER SET utf8 ;
USE `PuntoVenta` ;

-- -----------------------------------------------------
-- Table `PuntoVenta`.`Clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PuntoVenta`.`Clientes` (
  `rfc` VARCHAR(16) NOT NULL,
  `razonSocial` VARCHAR(100) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(10) NOT NULL,
  `calle` VARCHAR(45) NOT NULL,
  `numExt` INT NOT NULL,
  `numInt` VARCHAR(5) NULL,
  `colonia` VARCHAR(45) NOT NULL,
  `ciudad` VARCHAR(45) NOT NULL,
  `estado` VARCHAR(45) NOT NULL,
  `pais` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`rfc`))
ENGINE = InnoDB;

CREATE UNIQUE INDEX `rfc_UNIQUE` ON `PuntoVenta`.`Clientes` (`rfc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PuntoVenta`.`Conceptos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PuntoVenta`.`Conceptos` (
  `idConcepto` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `importe` DECIMAL(8,2) NOT NULL,
  `idRefaccion` INT NOT NULL,
  PRIMARY KEY (`idConcepto`),
  CONSTRAINT `fk_Conceptos_Refacciones1`
    FOREIGN KEY (`idRefaccion`)
    REFERENCES `PuntoVenta`.`Refacciones` (`idRefaccion`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Conceptos_Refacciones1_idx` ON `PuntoVenta`.`Conceptos` (`idRefaccion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PuntoVenta`.`Refacciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PuntoVenta`.`Refacciones` (
  `idRefaccion` INT NOT NULL,
  `nombre` VARCHAR(100) NOT NULL,
  `precio` DECIMAL(8,2) NOT NULL,
  `cantidad` INT NOT NULL,
  `uniMedida` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idRefaccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PuntoVenta`.`Ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PuntoVenta`.`Ventas` (
  `numVenta` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `rfc` VARCHAR(16) NOT NULL,
  `vehiculo` VARCHAR(100) NOT NULL,
  `total` DECIMAL(9,2) NOT NULL,
  PRIMARY KEY (`numVenta`),
  CONSTRAINT `fk_Ventas_Clientes`
    FOREIGN KEY (`rfc`)
    REFERENCES `PuntoVenta`.`Clientes` (`rfc`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE INDEX `fk_Ventas_Clientes_idx` ON `PuntoVenta`.`Ventas` (`rfc` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `PuntoVenta`.`VentasConceptos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PuntoVenta`.`VentasConceptos` (
  `numVenta` INT NOT NULL,
  `idConcepto` INT NOT NULL,
  PRIMARY KEY (`numVenta`, `idConcepto`),
  CONSTRAINT `fk_Ventas_has_Conceptos_Ventas1`
    FOREIGN KEY (`numVenta`)
    REFERENCES `PuntoVenta`.`Ventas` (`numVenta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Ventas_has_Conceptos_Conceptos1`
    FOREIGN KEY (`idConcepto`)
    REFERENCES `PuntoVenta`.`Conceptos` (`idConcepto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_Ventas_has_Conceptos_Conceptos1_idx` ON `PuntoVenta`.`VentasConceptos` (`idConcepto` ASC) VISIBLE;

CREATE INDEX `fk_Ventas_has_Conceptos_Ventas1_idx` ON `PuntoVenta`.`VentasConceptos` (`numVenta` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
